### ISSUE TITLE
types not exported correctly

### ISSUE THREAD

**Issue by cloudkite** [Hexagon/base64#184]
Types are not being picked up in my project, heres a minimal reproduction:

https://stackblitz.com/edit/vitejs-vite-ayep6m?file=src%2Fmain.ts

![CleanShot 2024-06-22 at 16 27 33@2x](https://github.com/Hexagon/base64/assets/598870/27d20c84-6619-4ae8-9de7-eb9754c3483f)

I think this has todo with the following settings in tsconfig

```
"moduleResolution": "Bundler",
"module": "ESNext",
```

I could resolve this by patching @hexagon/base64 package.json to the following:

```patch
   "exports": {
     ".": {
-      "import": "./src/base64.js",
+      "import": {"default":"./src/base64.js", "types":"./types/base64.d.ts"},
       "require": "./dist/base64.cjs",
       "browser": "./dist/base64.min.js"
     }
```

**Comment by cloudkite** [comment]
Also this might be helpful https://www.npmjs.com/package/@arethetypeswrong/cli

https://arethetypeswrong.github.io/?p=%40hexagon%2Fbase64%401.1.28.

**Comment by evert** [comment]
Same here! Only started showing up once i switched to esm

**Comment by Hexagon** [comment]
I'm working on a new major release simplifying the build process, check if 
 2.0.0-dev.1 (`npm i @hexagon/base64@dev`) works better

**Comment by chrisspiegl** [comment]
I installed the `2.0.0-dev.1` and the types show up and it looks fine.

<img width="1209" alt="Xnapper-2024-09-05-18 56 06" src="https://github.com/user-attachments/assets/290ed0b0-d87e-46f5-b8ea-2f48b50dc270">

<img width="1275" alt="Xnapper-2024-09-05-18 56 19" src="https://github.com/user-attachments/assets/157f537d-1256-4c34-92bc-ff993f3d114d">

**Comment by cloudkite** [comment]
@Hexagon sorry for the delayed response. Can confirm that `2.0.0-dev.1` works for me as well

**Comment by Hexagon** [comment]
Do `2.0.0-dev.3` work as well? Made some drastic changes (switched from dnt to esbuild).

**Comment by cloudkite** [comment]
> Thanks! Does `2.0.0-dev.3` work as well? I made some drastic changes (switched from dnt to esbuild).

yup 2.0.0-dev.3 works for me as well

**Comment by Hexagon** [comment]
Thanks! Will release asap

**Comment by chrisspiegl** [comment]
Just wanted to confirm that I also successfully tested the dev.3 version.

**Comment by Hexagon** [comment]
Thanks!

`2.0.0` is released now
